# -*- coding: utf-8 -*-
"""out/*.json → joy-relief-station に貼れる TypeScript / 案内人ページ用 JS を書き出す。
   使い方: python3 emit_ts.py --out <outdir>
"""
import json, os, sys, re

def load(d, n):
    return json.load(open(os.path.join(d, n), encoding="utf-8"))

def main():
    out = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else "out"
    arts = load(out, "yomi-artists.json")          # name -> yomi
    songs = load(out, "yomi-songs.json")           # artistId -> {title: yomi}
    detail = load(out, "yomi-artists.detail.json")
    review = load(out, "yomi-review.json")

    # 案内人が検索を呼ばずに口にしがちな「英字なのに日本のアーティスト」だけ、
    # 指示文に直接埋める（数が少ないのでトークンを食わない）。
    LAT = re.compile(r'^[\x00-\x7F]+$')
    hot = {}
    for e in detail:
        n, y = e["name"], e["yomi"]
        if not y or e["band"] not in ("green", "yellow"):
            continue
        if not LAT.match(n):
            continue
        risky = (e["src"].startswith("既知辞書")            # 日本の英字名として手で入れたもの
                 or (len(n) >= 3 and n.isupper())            # YOASOBI / RADWIMPS 型
                 or re.search(r'[0-9&+*#/_]', n))            # 数字・記号入り
        if risky:
            hot[n] = y
    hot = dict(sorted(hot.items()))

    ts = ['// AUTO-GENERATED by tools/yomi/build_yomi.py + emit_ts.py — 手で書き換えない。',
          '// 案内人（アイリス）に名前を正しく読ませるための読み辞書。',
          '// 出どころ: coverGuide.ts の aliases / 名前そのもの / id のローマ字 / 形態素解析。',
          '// 「危ないもの」は tools/yomi/out/yomi-review.json に分けてある。',
          '',
          'export const ARTIST_YOMI: Record<string, string> = ' +
          json.dumps(arts, ensure_ascii=False, indent=0, sort_keys=True) + ';',
          '',
          'export const SONG_YOMI: Record<string, Record<string, string>> = ' +
          json.dumps(songs, ensure_ascii=False, indent=0, sort_keys=True) + ';',
          '',
          '/** 検索を通らずに口に出しやすい、英字表記の名前だけを指示文へ入れる用 */',
          'export const HOT_YOMI: Record<string, string> = ' +
          json.dumps(hot, ensure_ascii=False, indent=0, sort_keys=True) + ';',
          '',
          'export function yomiOf(name: string): string | undefined {',
          '  if (!name) return undefined;',
          '  return ARTIST_YOMI[name] ?? ARTIST_YOMI[name.trim()];',
          '}',
          '',
          'export function songYomiOf(artistId: string, title: string): string | undefined {',
          '  return SONG_YOMI[artistId]?.[title];',
          '}',
          '',
          '/** 検索結果を案内人へ返す直前に通す。name の横に yomi を足すだけ（元データは壊さない）。 */',
          'export function withYomi<T>(value: T, artistId?: string): T {',
          '  const walk = (v: any, aid?: string): any => {',
          '    if (Array.isArray(v)) return v.map((x) => walk(x, aid));',
          '    if (v && typeof v === "object") {',
          '      const o: any = { ...v };',
          '      const id = o.artistId ?? o.artist ?? (o.songs ? o.id : undefined) ?? aid;',
          '      if (typeof o.name === "string") {',
          '        const y = yomiOf(o.name);',
          '        if (y) o.yomi = y;',
          '      }',
          '      if (typeof o.title === "string" && id) {',
          '        const y = songYomiOf(id, o.title);',
          '        if (y) o.titleYomi = y;',
          '      }',
          '      for (const k of Object.keys(o)) {',
          '        if (k !== "yomi" && k !== "titleYomi") o[k] = walk(o[k], id);',
          '      }',
          '      return o;',
          '    }',
          '    return v;',
          '  };',
          '  return walk(value, artistId);',
          '}',
          '',
          '/** 案内人の instructions の末尾に必ず足す1ブロック。 */',
          'export const YOMI_INSTRUCTION = [',
          '  "【名前の読み方・絶対厳守】",',
          '  "検索結果に yomi / titleYomi が付いているものは、必ずそのカタカナのとおりに発音する。",',
          '  "英字のつづりを見て英語読みに直さない。カタカナが正。",',
          '  "yomi が無い英字名だけ、そのまま英語として読んでよい。",',
          '  "下の名前は検索を通さずに口に出すことがあるので、ここに書いた読みで固定する：",',
          '  Object.entries(HOT_YOMI).map(([n, y]) => `${n}=${y}`).join("／"),',
          ']. join("\\n");',
          '']
    src = "\n".join(ts).replace(']. join', '].join')
    open(os.path.join(out, "yomiDictionary.ts"), "w", encoding="utf-8").write(src)

    # 案内人ページ（素のHTML版）から読み込む用の JS。辞書＋使う関数を同梱する。
    js = ("// AUTO-GENERATED by tools/yomi/build_yomi.py + emit_ts.py — 手で書き換えない。\n"
          "window.TAMAGO_YOMI = " + json.dumps(
              {"artists": arts, "songs": songs, "hot": hot},
              ensure_ascii=False, sort_keys=True) + ";\n"
          + r'''
window.TAMAGO_YOMI.of = function (name) {
  if (!name) return undefined;
  var d = window.TAMAGO_YOMI.artists;
  return d[name] || d[String(name).trim()];
};
window.TAMAGO_YOMI.songOf = function (artistId, title) {
  var s = window.TAMAGO_YOMI.songs[artistId];
  return s ? s[title] : undefined;
};
/** 検索結果を案内人へ返す直前に通す。name の横に yomi を足すだけ。 */
window.TAMAGO_YOMI.decorate = function (value, artistId) {
  function walk(v, aid) {
    if (Array.isArray(v)) return v.map(function (x) { return walk(x, aid); });
    if (v && typeof v === "object") {
      var o = {}; for (var k in v) o[k] = v[k];
      var id = o.artistId || o.artist || (o.songs ? o.id : undefined) || aid;
      if (typeof o.name === "string") {
        var y = window.TAMAGO_YOMI.of(o.name); if (y) o.yomi = y;
      }
      if (typeof o.title === "string" && id) {
        var ty = window.TAMAGO_YOMI.songOf(id, o.title); if (ty) o.titleYomi = ty;
      }
      for (var k2 in o) { if (k2 !== "yomi" && k2 !== "titleYomi") o[k2] = walk(o[k2], id); }
      return o;
    }
    return v;
  }
  return walk(value, artistId);
};
/** 案内人の instructions の末尾に必ず足す1ブロック。 */
window.TAMAGO_YOMI.instruction = function () {
  var hot = window.TAMAGO_YOMI.hot;
  return [
    "【名前の読み方・絶対厳守】",
    "検索結果に yomi / titleYomi が付いているものは、必ずそのカタカナのとおりに発音する。",
    "英字のつづりを見て英語読みに直さない。カタカナが正。",
    "yomi が無い英字名だけ、そのまま英語として読んでよい。",
    "次の名前は検索を通さずに口に出すことがあるので、ここに書いた読みで固定する：",
    Object.keys(hot).map(function (n) { return n + "=" + hot[n]; }).join("／")
  ].join("\n");
};
''')
    open(os.path.join(out, "yomi.js"), "w", encoding="utf-8").write(js)

    red = [r for r in review if r.get("band") == "red"]
    yellow = [r for r in review if r.get("band") == "yellow"]
    print(json.dumps({"artists": len(arts), "songs": sum(len(v) for v in songs.values()),
                      "hot": len(hot), "red": len(red), "yellow": len(yellow)},
                     ensure_ascii=False, indent=1))

if __name__ == "__main__":
    main()
